# Generated by Django 3.0.7 on 2020-07-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0016_auto_20200727_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentSystems.BitcoinPayment')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Purchase')),
            ],
        ),
    ]
