# Generated by Django 3.0.7 on 2020-06-30 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cheat_images', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('last_detect_at', models.DateTimeField(blank=True, null=True, verbose_name='Detection date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Update date')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='game_images', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('payment', models.CharField(max_length=16, verbose_name='Payment method')),
                ('payment_id', models.CharField(max_length=64, verbose_name='Payment method')),
                ('status', models.CharField(max_length=16, verbose_name='Status')),
                ('key', models.CharField(max_length=32, verbose_name='Key')),
                ('cheat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Cheat', verbose_name='Cheat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='cheat',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Game', verbose_name='Game'),
        ),
    ]
