# Generated by Django 3.0.7 on 2020-07-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200701_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='key',
            field=models.CharField(blank=True, max_length=32, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment',
            field=models.CharField(choices=[('Card', 'Card'), ('Bitcoin', 'Bitcoin'), ('PayPal', 'PayPal')], max_length=16, verbose_name='Payment method'),
        ),
    ]
