# Generated by Django 3.0.7 on 2020-07-01 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200701_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cheat_images', verbose_name='Image')),
                ('cheat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cheat', verbose_name='Cheat')),
            ],
        ),
    ]
