# Generated by Django 3.0.7 on 2020-07-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cheatvideos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheatVideos',
            new_name='CheatVideo',
        ),
    ]
