# Generated by Django 3.0.7 on 2020-07-06 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cheat_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheat',
            name='price',
        ),
        migrations.AddField(
            model_name='cheat',
            name='hardware_support',
            field=models.CharField(blank=True, max_length=64, verbose_name='Hardware Support'),
        ),
        migrations.AddField(
            model_name='key',
            name='plan',
            field=models.CharField(default='30 days', max_length=64, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='cheat',
            name='oc_support',
            field=models.CharField(blank=True, max_length=64, verbose_name='OC Support'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(null=True, upload_to='game_images', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('plan', models.CharField(default='30 days', max_length=64, verbose_name='Plan')),
                ('cheat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cheat', verbose_name='Cheat')),
            ],
        ),
    ]
