# Generated by Django 3.0.7 on 2020-07-07 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200706_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Key', verbose_name='Лун'),
        ),
    ]
