# Generated by Django 3.0.7 on 2020-07-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200706_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='Name')),
                ('ds_server_id', models.IntegerField(blank=True, null=True, verbose_name='Discord server ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='cheat',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='key',
        ),
        migrations.AddField(
            model_name='cheat',
            name='ds_role_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discord role ID'),
        ),
        migrations.AddField(
            model_name='key',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Purchase', verbose_name='Purchase'),
        ),
        migrations.CreateModel(
            name='PurchaseDSLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_link', models.CharField(max_length=32, verbose_name='Server link')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Purchase', verbose_name='Purchase')),
            ],
        ),
        migrations.AddField(
            model_name='cheat',
            name='ds_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.DSServer', verbose_name='Discord server'),
        ),
    ]
