# Generated by Django 3.0.7 on 2020-07-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_last_hit_to_hit_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsserver',
            name='is_common',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is common'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='hit_at',
            field=models.DateTimeField(verbose_name='Hit at'),
        ),
    ]
