# Generated by Django 3.0.7 on 2020-07-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200707_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='button_link',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Button link'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='button_text',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Button text'),
        ),
    ]
