# Generated by Django 3.0.7 on 2020-07-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200710_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='plan',
        ),
        migrations.AddField(
            model_name='price',
            name='duration',
            field=models.IntegerField(default='30', verbose_name='Duration in days'),
        ),
    ]
