# Generated by Django 3.0.7 on 2020-07-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200711_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='payment',
            new_name='payment_method',
        ),
    ]
