# Generated by Django 3.0.7 on 2020-07-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DSServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='Name')),
                ('ds_server_id', models.IntegerField(blank=True, null=True, verbose_name='Discord server ID')),
                ('is_common', models.BooleanField(blank=True, default=False, verbose_name='Is common?')),
            ],
        ),
    ]
