# Generated by Django 3.0.7 on 2020-07-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DSServer',
        ),
    ]
